name: Build and Release Windows
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Setup MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        
    - name: Install Qt 6.8.1
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.1'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        tools: 'tools_cmake tools_ninja'
      
    - name: Configure project with qmake
      run: qmake OnBoarder.pro CONFIG+=release
      
    - name: Build project
      run: nmake
      
    - name: Deploy Qt dependencies
      run: |
        mkdir deploy
        copy release\OnBoarder.exe deploy\
        windeployqt deploy\OnBoarder.exe --release --no-translations --no-system-d3d-compiler --no-opengl-sw
        
    - name: Create ZIP package
      run: powershell Compress-Archive -Path "deploy\*" -DestinationPath "OnBoarder.zip"
      
    - name: Verify package exists
      run: dir OnBoarder.zip
      
    - name: Install Velopack CLI
      run: |
        $env:MSBuildSDKsPath=""
        dotnet tool install vpk --version 0.0.1298 --global
      shell: powershell
    
    - name: Create Velopack release
      run: |
        $version = "${{ github.ref_name }}" -replace '^v', ''
        Write-Output "Using version: $version"
        
        vpk pack `
          --packDir deploy `
          --packId OnBoarder `
          --packVersion $version `
          --mainExe OnBoarder.exe `
          --outputDir Releases
      shell: powershell
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        name: OnBoarder ${{ github.ref_name }}
        body: |
          🚀 **OnBoarder ${{ github.ref_name }}** - Application Manager for Windows
          
          ## 📦 Download
          Download `OnBoarder.zip` below
          
          ## 💻 System Requirements
          - Windows 10/11 (64-bit)
          - All Qt dependencies included in the ZIP
        files: |
          OnBoarder.zip
          Releases/*
        draft: false
        prerelease: false
        generate_release_notes: false
